# Load Packages

In [4]:
# usuals
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os

# sklearn
from sklearn.model_selection import train_test_split

# Load Datasets

In [29]:
AADT_df = pd.read_csv('Annual_Average_Daily_Traffic_Historical.csv')
display(AADT_df.head())
display(AADT_df.shape)
AADT_df.columns

,FID,YEAR_,DISTRICT,COSITE,ROADWAY,DESC_FRM,DESC_TO,AADT,AADTFLG,KFLG,...,END_POST,KFCTR,K100FCTR,DFCTR,TFCTR,Shape_Leng,COUNTYDOT,COUNTY,MNG_DIST,Shape__Length
0,1,2021,5,970534,75471000,Bridge No-750093,Bridge No-750099,74000,C,F,...,8.150,9.0,0,59.6,10.1,5803.6764,75,Orange,8,5803.676358
1,2,2021,5,368110,36000151,SW 7 AVE,US27/US301/US441 S,20500,F,F,...,0.953,9.0,0,53.2,8.5,1533.2738,36,Marion,5,1533.273812
2,3,2021,5,365049,36040000,US-301/441/PINE AVE,NE 35 ST,9000,F,F,...,1.787,9.0,0,53.2,7.1,2885.4491,36,Marion,5,2885.449059
3,4,2021,2,350279,35010000,SW CAPTAIN BROWN RD,CR-360A/MLK JR DR,8243,C,A,...,19.686,9.5,0,61.7,6.8,885.3673,35,Madison,2,885.367348
4,5,2021,5,368050,36000124,CR 484,SW 41 PL,2500,C,F,...,6.442,9.0,0,53.2,8.5,10370.2109,36,Marion,5,10370.210915

(103667, 24)

Index(['FID', 'YEAR_', 'DISTRICT', 'COSITE', 'ROADWAY', 'DESC_FRM', 'DESC_TO',
       'AADT', 'AADTFLG', 'KFLG', 'K100FLG', 'DFLG', 'TFLG', 'BEGIN_POST',
       'END_POST', 'KFCTR', 'K100FCTR', 'DFCTR', 'TFCTR', 'Shape_Leng',
       'COUNTYDOT', 'COUNTY', 'MNG_DIST', 'Shape__Length'],
      dtype='object')

In [27]:
FC_df = pd.read_csv('Functional_Classification.csv')
display(FC_df.head())
display(FC_df.shape)
FC_df.columns

,FID,ROADWAY,FUNCLASS,BEGIN_POST,END_POST,Shape_Leng,DISTRICT,COUNTYDOT,COUNTY,MNG_DIST,Shape__Length
0,1,38650000,9,0.306,0.507,323.6383,2,38,Taylor,2,323.638319
1,2,77503000,18,0.000,2.263,3636.0321,5,77,Seminole,5,3636.032138
2,3,14000126,17,0.000,2.492,3985.3246,7,14,Pasco,7,3985.324615
3,4,1000024,17,0.394,1.458,1721.3414,1,1,Charlotte,1,1721.341439
4,5,1512000,17,0.000,1.703,2740.8256,1,1,Charlotte,1,2740.825618

(17134, 11)

Index(['FID', 'ROADWAY', 'FUNCLASS', 'BEGIN_POST', 'END_POST', 'Shape_Leng',
       'DISTRICT', 'COUNTYDOT', 'COUNTY', 'MNG_DIST', 'Shape__Length'],
      dtype='object')

In [25]:
TV_df = pd.read_csv('Truck_Volume.csv')
display(TV_df.head())
display(TV_df.shape)
TV_df.columns

,FID,YEAR_,DISTRICT,COSITE,ROADWAY,AADT,AADTFLG,KFLG,K100FLG,DFLG,...,K100FCTR,DFCTR,TFCTR,Shape_Leng,DESC_FRM,DESC_TO,COUNTYDOT,COUNTY,MNG_DIST,Shape__Length
0,1,2025,2,380018,38010000,11100,C,F,F,F,...,0,55.6,12.3,1328.4235,NaN,NaN,38,Taylor,2,1328.423473
1,2,2025,7,146033,14610000,51000,C,F,F,F,...,0,55.7,5.9,1612.6734,COUNTY LINE RD,SR-56,14,Pasco,7,1612.673355
2,3,2025,7,149075,14000202,850,C,F,F,F,...,0,55.7,7.2,556.1986,FIVAY RD,HUDSON AV,14,Pasco,7,556.198594
3,4,2025,7,29023,2000028,4100,C,F,F,F,...,0,52.8,9.1,1732.3796,S PLEASANT GROVE RD,S CASCADE AVE,2,Citrus,7,1732.379562
4,5,2025,2,719001,71000015,22000,F,F,F,F,...,0,52.7,1.3,4033.7424,SR-21,US-17/PARK AVE,71,Clay,2,4033.742382

(21612, 25)

Index(['FID', 'YEAR_', 'DISTRICT', 'COSITE', 'ROADWAY', 'AADT', 'AADTFLG',
       'KFLG', 'K100FLG', 'DFLG', 'TFLG', 'TruckAADT', 'BEGIN_POST',
       'END_POST', 'KFCTR', 'K100FCTR', 'DFCTR', 'TFCTR', 'Shape_Leng',
       'DESC_FRM', 'DESC_TO', 'COUNTYDOT', 'COUNTY', 'MNG_DIST',
       'Shape__Length'],
      dtype='object')

# Sources:
- https://gis-fdot.opendata.arcgis.com/datasets/fdot%3A%3Aannual-average-daily-traffic-historical-tda/about
- https://gis-fdot.opendata.arcgis.com/datasets/fdot%3A%3Atruck-volume-tda/about
- https://gis-fdot.opendata.arcgis.com/datasets/fdot%3A%3Afunctional-classification-tda/about
- https://gis-fdot.opendata.arcgis.com/datasets/fdot%3A%3Aaccess-management-tda/about
- https://gis-fdot.opendata.arcgis.com/datasets/fdot%3A%3Atraffic-signal-locations-tda/about